### ISSUE TITLE
Environment created by graders should be kept and used

### ISSUE THREAD

**Issue by qcoumes** [plgitlogin/sandbox#21]
Currently, the environment used to grade exercise is always `[ENV_ID]_built.tgz`.

The one created by the grader should be saved and used if available.

Related to [this issue on PL](https://github.com/PremierLangage/premierlangage/issues/130)

**Comment by nimdanor** [comment]
Be carefull because the Activity will be able to change the pl before sending it back to playexo and the sandbox ...

I will draw the cycle of the pl through the different parts. 

DB -> activity -> playexo -> sandbox -> builder -> X -> playexo -> sandbox -> grader -> activity ->  restart the cycle from X.

**Comment by qcoumes** [comment]
I created a specific issue for this: #22

**Comment by qcoumes** [comment]
Solved on 1.0.0
