### ISSUE TITLE
Why is the CMD  Bash ?

### ISSUE THREAD

**Issue by plgitlogin** [plgitlogin/sandbox#8]
Can't we use a DockerFile adapted to python, and the app.py is the grader.py file ?? 
Or do we need to do updating work ?? 
The following DockerFile is python specific is it better or worst ?

```bash
# Use an official Python runtime as a parent image
FROM python:2.7-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python", "app.py"]

```

**Comment by qcoumes** [comment]
I don't see your point.

The given DockerFile just run  `python3 app.py` (python 2.7 actually from the given parent image)  as soon as the container is launched, instead of waiting for any bash command. Except for the nanoseconds used by bash to start python3, it won't be any faster.

Moreover, it is not compatible with a pool of running container since the container is executing the script at launch then stopped.

**Comment by nimdanor** [comment]
ok
